## NOTEBOOK IMPORTS

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('sales', axis=1)
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [6]:
poly_features = polynomial_converter.fit_transform(X)

In [7]:
poly_features.shape

(200, 19)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()

In [11]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [12]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [13]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

## RIDGE REGRESSION - L2 Regularization

In [14]:
from sklearn.linear_model import Ridge

In [15]:
help(Ridge)

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(alpha=1.0, *, fit_intercept=True, normalize=False, copy_X=True, max_iter=None, tol=0.001, solver='auto', random_state=None)
 |  
 |  Linear least squares with l2 regularization.
 |  
 |  Minimizes the objective function::
 |  
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |  
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Regularization strength; must be a positive float. Regul

In [16]:
ridge_model = Ridge(alpha=10)

In [17]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [18]:
test_predictions = ridge_model.predict(X_test)

In [19]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [20]:
MAE = mean_absolute_error(y_test, test_predictions)

In [21]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [22]:
MAE

0.9670410375853888

In [23]:
RMSE

1.332761154538626

In [24]:
from sklearn.linear_model import RidgeCV

In [25]:
ridgecv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_squared_error')

In [26]:
ridgecv_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_squared_error')

In [27]:
ridgecv_model.alpha_

0.1

In [28]:
from sklearn.metrics import SCORERS

In [29]:
#SCORERS.keys()

In [30]:
test_predictions = ridgecv_model.predict(X_test)

In [31]:
MAE = mean_absolute_error(y_test, test_predictions)

In [32]:
MAE

0.9873965312436981

In [33]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [34]:
RMSE

1.1676689886078184

In [35]:
ridgecv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [36]:
ridgecv_model.best_score_

-0.3777066848707344

## LASSO REGRESSION - L1 Regularization

### Least Absolute Shrinkage and Selection Operator (LASSO)

In [37]:
from sklearn.linear_model import LassoCV

In [38]:
lassocv_model = LassoCV(eps=0.001, n_alphas=100, cv=5, max_iter=100000)

In [39]:
lassocv_model.fit(X_train, y_train)

LassoCV(cv=5, max_iter=100000)

In [40]:
test_predictions = lassocv_model.predict(X_test)

In [41]:
lassocv_model.alpha_

0.004943070909225827

In [42]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.9723939145391846

In [43]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

1.1570105786801903

In [44]:
lassocv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])